// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bvaveefsctnpkwydbgsg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ2YXZlZWZzY3RucGt3eWRiZ3NnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyMTI2OTgsImV4cCI6MjA1OTc4ODY5OH0.XiaC3qlVWn94nftEH-FY77q0MCv_Yqjq7IG5sIu_ClY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);