
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bvaveefsctnpkwydbgsg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ2YXZlZWZzY3RucGt3eWRiZ3NnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyMTI2OTgsImV4cCI6MjA1OTc4ODY5OH0.XiaC3qlVWn94nftEH-FY77q0MCv_Yqjq7IG5sIu_ClY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Force TypeScript to correctly recognize the database tables
declare module '@supabase/supabase-js' {
  interface Database {
    public: {
      Tables: {
        admin_settings: {
          Row: {
            id: number;
            time_slots: string[] | null;
            max_guests_per_day: number | null;
            google_connected: boolean | null;
            google_refresh_token: string | null;
            google_email: string | null;
            last_sync_timestamp: string | null;
            last_sync_status: string | null;
            sync_error: string | null;
            created_at: string | null;
            updated_at: string | null;
          };
        };
        events: {
          Row: {
            id: string;
            title: string;
            description: string;
            image: string;
            date: string;
            time: string;
            created_at: string | null;
            updated_at: string | null;
          };
        };
        menu_items: {
          Row: {
            id: string;
            name: string;
            description: string;
            price: number;
            category: string;
            image: string;
            featured: boolean | null;
            created_at: string | null;
            updated_at: string | null;
          };
        };
        reservations: {
          Row: {
            id: string;
            name: string;
            date: string;
            time: string;
            guests: number;
            phone: string;
            email: string;
            notes: string | null;
            google_event_id: string | null;
            imported_from_google: boolean | null;
            created_at: string | null;
            updated_at: string | null;
          };
        };
      };
    };
  }
}
